
name: pyQMark

on:
  issue_comment:
    types: [created]

jobs:
  issue_comment_created:

    if: (${{ !github.event.issue.pull_request }}) && (${{ github.event.issue.number }}==1)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run pyQMark
      run: |
        python action/issuecomment.py ${{ secrets.GITHUB_TOKEN }} ${{ github.event.issue.url }} ${{ github.event.comment.body }}
